export type StrategyName = typeof availableStrategies[number]

export const inverseStrategies = [
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_10_ETH",
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_10_BTC",
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_20_ETH",
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_20_BTC",
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_30_ETH",
  "HegicStrategy_INVERSE_BEAR_CALL_SPREAD_30_BTC",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_10_ETH",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_10_BTC",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_20_ETH",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_20_BTC",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_30_ETH",
  "HegicStrategy_INVERSE_BULL_PUT_SPREAD_30_BTC",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_10_ETH",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_10_BTC",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_20_ETH",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_20_BTC",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_30_ETH",
  "HegicStrategy_INVERSE_LONG_BUTTERFLY_30_BTC",
  "HegicStrategy_INVERSE_LONG_CONDOR_20_ETH",
  "HegicStrategy_INVERSE_LONG_CONDOR_20_BTC",
  "HegicStrategy_INVERSE_LONG_CONDOR_30_ETH",
  "HegicStrategy_INVERSE_LONG_CONDOR_30_BTC",
] as const

export const v0Strategies = [
  "HegicStrategy_v0_CALL_100_BTC",
  "HegicStrategy_v0_CALL_100_ETH",
  "HegicStrategy_v0_CALL_110_BTC",
  "HegicStrategy_v0_CALL_110_ETH",
  "HegicStrategy_v0_CALL_120_BTC",
  "HegicStrategy_v0_CALL_120_ETH",
  "HegicStrategy_v0_CALL_130_BTC",
  "HegicStrategy_v0_CALL_130_ETH",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_10_BTC",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_10_ETH",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_20_BTC",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_20_ETH",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_30_BTC",
  "HegicStrategy_v0_INVERSE_BEAR_CALL_SPREAD_30_ETH",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_10_BTC",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_10_ETH",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_20_BTC",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_20_ETH",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_30_BTC",
  "HegicStrategy_v0_INVERSE_BULL_PUT_SPREAD_30_ETH",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_10_BTC",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_10_ETH",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_20_BTC",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_20_ETH",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_30_BTC",
  "HegicStrategy_v0_INVERSE_LONG_BUTTERFLY_30_ETH",
  "HegicStrategy_v0_INVERSE_LONG_CONDOR_20_BTC",
  "HegicStrategy_v0_INVERSE_LONG_CONDOR_20_ETH",
  "HegicStrategy_v0_INVERSE_LONG_CONDOR_30_BTC",
  "HegicStrategy_v0_INVERSE_LONG_CONDOR_30_ETH",
  "HegicStrategy_v0_PUT_100_BTC",
  "HegicStrategy_v0_PUT_100_ETH",
  "HegicStrategy_v0_PUT_70_BTC",
  "HegicStrategy_v0_PUT_70_ETH",
  "HegicStrategy_v0_PUT_80_BTC",
  "HegicStrategy_v0_PUT_80_ETH",
  "HegicStrategy_v0_PUT_90_BTC",
  "HegicStrategy_v0_PUT_90_ETH",
  "HegicStrategy_v0_SPREAD_CALL_10_BTC",
  "HegicStrategy_v0_SPREAD_CALL_10_ETH",
  "HegicStrategy_v0_SPREAD_CALL_20_BTC",
  "HegicStrategy_v0_SPREAD_CALL_20_ETH",
  "HegicStrategy_v0_SPREAD_CALL_30_BTC",
  "HegicStrategy_v0_SPREAD_CALL_30_ETH",
  "HegicStrategy_v0_SPREAD_PUT_10_BTC",
  "HegicStrategy_v0_SPREAD_PUT_10_ETH",
  "HegicStrategy_v0_SPREAD_PUT_20_BTC",
  "HegicStrategy_v0_SPREAD_PUT_20_ETH",
  "HegicStrategy_v0_SPREAD_PUT_30_BTC",
  "HegicStrategy_v0_SPREAD_PUT_30_ETH",
  "HegicStrategy_v0_STRADDLE_BTC",
  "HegicStrategy_v0_STRADDLE_ETH",
  "HegicStrategy_v0_STRANGLE_10_BTC",
  "HegicStrategy_v0_STRANGLE_10_ETH",
  "HegicStrategy_v0_STRANGLE_20_BTC",
  "HegicStrategy_v0_STRANGLE_20_ETH",
  "HegicStrategy_v0_STRANGLE_30_BTC",
  "HegicStrategy_v0_STRANGLE_30_ETH",
  "HegicStrategy_v0_STRAP_BTC",
  "HegicStrategy_v0_STRAP_ETH",
  "HegicStrategy_v0_STRIP_BTC",
  "HegicStrategy_v0_STRIP_ETH",
] as const


export type StrategyType =
  | "PUT"
  | "CALL"
  | "INVERSE_BEAR_CALL_SPREAD"
  | "INVERSE_BULL_PUT_SPREAD"
  | "STRADDLE"
  | "STRANGLE"
  | "INVERSE_LONG_BUTTERFLY"
  | "INVERSE_LONG_CONDOR"
  | "SPREAD_CALL"
  | "SPREAD_PUT"
  | "STRAP"
  | "STRIP"

export const classicStrategies = [
  "HegicStrategy_CALL_100_ETH_1",
  "HegicStrategy_CALL_100_ETH_2",
  "HegicStrategy_CALL_100_ETH_3",
  "HegicStrategy_CALL_100_ETH_4",
  "HegicStrategy_CALL_110_ETH_1",
  "HegicStrategy_CALL_110_ETH_2",
  "HegicStrategy_CALL_110_ETH_3",
  "HegicStrategy_CALL_110_ETH_4",
  "HegicStrategy_CALL_120_ETH_1",
  "HegicStrategy_CALL_120_ETH_2",
  "HegicStrategy_CALL_120_ETH_3",
  "HegicStrategy_CALL_120_ETH_4",
  "HegicStrategy_CALL_130_ETH_1",
  "HegicStrategy_CALL_130_ETH_2",
  "HegicStrategy_CALL_130_ETH_3",
  "HegicStrategy_CALL_130_ETH_4",
  "HegicStrategy_PUT_100_ETH_1",
  "HegicStrategy_PUT_100_ETH_2",
  "HegicStrategy_PUT_100_ETH_3",
  "HegicStrategy_PUT_100_ETH_4",
  "HegicStrategy_PUT_90_ETH_1",
  "HegicStrategy_PUT_90_ETH_2",
  "HegicStrategy_PUT_90_ETH_3",
  "HegicStrategy_PUT_90_ETH_4",
  "HegicStrategy_PUT_80_ETH_1",
  "HegicStrategy_PUT_80_ETH_2",
  "HegicStrategy_PUT_80_ETH_3",
  "HegicStrategy_PUT_80_ETH_4",
  "HegicStrategy_PUT_70_ETH_1",
  "HegicStrategy_PUT_70_ETH_2",
  "HegicStrategy_PUT_70_ETH_3",
  "HegicStrategy_PUT_70_ETH_4",
  "HegicStrategy_SPREAD_CALL_10_ETH_1",
  "HegicStrategy_SPREAD_CALL_10_ETH_2",
  "HegicStrategy_SPREAD_CALL_10_ETH_3",
  "HegicStrategy_SPREAD_CALL_10_ETH_4",
  "HegicStrategy_SPREAD_CALL_20_ETH_1",
  "HegicStrategy_SPREAD_CALL_20_ETH_2",
  "HegicStrategy_SPREAD_CALL_20_ETH_3",
  "HegicStrategy_SPREAD_CALL_20_ETH_4",
  "HegicStrategy_SPREAD_CALL_30_ETH_1",
  "HegicStrategy_SPREAD_CALL_30_ETH_2",
  "HegicStrategy_SPREAD_CALL_30_ETH_3",
  "HegicStrategy_SPREAD_CALL_30_ETH_4",
  "HegicStrategy_SPREAD_PUT_10_ETH_1",
  "HegicStrategy_SPREAD_PUT_10_ETH_2",
  "HegicStrategy_SPREAD_PUT_10_ETH_3",
  "HegicStrategy_SPREAD_PUT_10_ETH_4",
  "HegicStrategy_SPREAD_PUT_20_ETH_1",
  "HegicStrategy_SPREAD_PUT_20_ETH_2",
  "HegicStrategy_SPREAD_PUT_20_ETH_3",
  "HegicStrategy_SPREAD_PUT_20_ETH_4",
  "HegicStrategy_SPREAD_PUT_30_ETH_1",
  "HegicStrategy_SPREAD_PUT_30_ETH_2",
  "HegicStrategy_SPREAD_PUT_30_ETH_3",
  "HegicStrategy_SPREAD_PUT_30_ETH_4",
  "HegicStrategy_STRADDLE_ETH_1",
  "HegicStrategy_STRADDLE_ETH_2",
  "HegicStrategy_STRADDLE_ETH_3",
  "HegicStrategy_STRADDLE_ETH_4",
  "HegicStrategy_STRAP_ETH_1",
  "HegicStrategy_STRAP_ETH_2",
  "HegicStrategy_STRAP_ETH_3",
  "HegicStrategy_STRAP_ETH_4",
  "HegicStrategy_STRIP_ETH_1",
  "HegicStrategy_STRIP_ETH_2",
  "HegicStrategy_STRIP_ETH_3",
  "HegicStrategy_STRIP_ETH_4",
  "HegicStrategy_STRANGLE_10_ETH_1",
  "HegicStrategy_STRANGLE_10_ETH_2",
  "HegicStrategy_STRANGLE_10_ETH_3",
  "HegicStrategy_STRANGLE_10_ETH_4",
  "HegicStrategy_STRANGLE_20_ETH_1",
  "HegicStrategy_STRANGLE_20_ETH_2",
  "HegicStrategy_STRANGLE_20_ETH_3",
  "HegicStrategy_STRANGLE_20_ETH_4",
  "HegicStrategy_STRANGLE_30_ETH_1",
  "HegicStrategy_STRANGLE_30_ETH_2",
  "HegicStrategy_STRANGLE_30_ETH_3",
  "HegicStrategy_STRANGLE_30_ETH_4",
  "HegicStrategy_CALL_100_BTC_1",
  "HegicStrategy_CALL_100_BTC_2",
  "HegicStrategy_CALL_100_BTC_3",
  "HegicStrategy_CALL_100_BTC_4",
  "HegicStrategy_CALL_110_BTC_1",
  "HegicStrategy_CALL_110_BTC_2",
  "HegicStrategy_CALL_110_BTC_3",
  "HegicStrategy_CALL_110_BTC_4",
  "HegicStrategy_CALL_120_BTC_1",
  "HegicStrategy_CALL_120_BTC_2",
  "HegicStrategy_CALL_120_BTC_3",
  "HegicStrategy_CALL_120_BTC_4",
  "HegicStrategy_CALL_130_BTC_1",
  "HegicStrategy_CALL_130_BTC_2",
  "HegicStrategy_CALL_130_BTC_3",
  "HegicStrategy_CALL_130_BTC_4",
  "HegicStrategy_PUT_100_BTC_1",
  "HegicStrategy_PUT_100_BTC_2",
  "HegicStrategy_PUT_100_BTC_3",
  "HegicStrategy_PUT_100_BTC_4",
  "HegicStrategy_PUT_90_BTC_1",
  "HegicStrategy_PUT_90_BTC_2",
  "HegicStrategy_PUT_90_BTC_3",
  "HegicStrategy_PUT_90_BTC_4",
  "HegicStrategy_PUT_80_BTC_1",
  "HegicStrategy_PUT_80_BTC_2",
  "HegicStrategy_PUT_80_BTC_3",
  "HegicStrategy_PUT_80_BTC_4",
  "HegicStrategy_PUT_70_BTC_1",
  "HegicStrategy_PUT_70_BTC_2",
  "HegicStrategy_PUT_70_BTC_3",
  "HegicStrategy_PUT_70_BTC_4",
  "HegicStrategy_SPREAD_CALL_10_BTC_1",
  "HegicStrategy_SPREAD_CALL_10_BTC_2",
  "HegicStrategy_SPREAD_CALL_10_BTC_3",
  "HegicStrategy_SPREAD_CALL_10_BTC_4",
  "HegicStrategy_SPREAD_CALL_20_BTC_1",
  "HegicStrategy_SPREAD_CALL_20_BTC_2",
  "HegicStrategy_SPREAD_CALL_20_BTC_3",
  "HegicStrategy_SPREAD_CALL_20_BTC_4",
  "HegicStrategy_SPREAD_CALL_30_BTC_1",
  "HegicStrategy_SPREAD_CALL_30_BTC_2",
  "HegicStrategy_SPREAD_CALL_30_BTC_3",
  "HegicStrategy_SPREAD_CALL_30_BTC_4",
  "HegicStrategy_SPREAD_PUT_10_BTC_1",
  "HegicStrategy_SPREAD_PUT_10_BTC_2",
  "HegicStrategy_SPREAD_PUT_10_BTC_3",
  "HegicStrategy_SPREAD_PUT_10_BTC_4",
  "HegicStrategy_SPREAD_PUT_20_BTC_1",
  "HegicStrategy_SPREAD_PUT_20_BTC_2",
  "HegicStrategy_SPREAD_PUT_20_BTC_3",
  "HegicStrategy_SPREAD_PUT_20_BTC_4",
  "HegicStrategy_SPREAD_PUT_30_BTC_1",
  "HegicStrategy_SPREAD_PUT_30_BTC_2",
  "HegicStrategy_SPREAD_PUT_30_BTC_3",
  "HegicStrategy_SPREAD_PUT_30_BTC_4",
  "HegicStrategy_STRADDLE_BTC_1",
  "HegicStrategy_STRADDLE_BTC_2",
  "HegicStrategy_STRADDLE_BTC_3",
  "HegicStrategy_STRADDLE_BTC_4",
  "HegicStrategy_STRAP_BTC_1",
  "HegicStrategy_STRAP_BTC_2",
  "HegicStrategy_STRAP_BTC_3",
  "HegicStrategy_STRAP_BTC_4",
  "HegicStrategy_STRIP_BTC_1",
  "HegicStrategy_STRIP_BTC_2",
  "HegicStrategy_STRIP_BTC_3",
  "HegicStrategy_STRIP_BTC_4",
  "HegicStrategy_STRANGLE_10_BTC_1",
  "HegicStrategy_STRANGLE_10_BTC_2",
  "HegicStrategy_STRANGLE_10_BTC_3",
  "HegicStrategy_STRANGLE_10_BTC_4",
  "HegicStrategy_STRANGLE_20_BTC_1",
  "HegicStrategy_STRANGLE_20_BTC_2",
  "HegicStrategy_STRANGLE_20_BTC_3",
  "HegicStrategy_STRANGLE_20_BTC_4",
  "HegicStrategy_STRANGLE_30_BTC_1",
  "HegicStrategy_STRANGLE_30_BTC_2",
  "HegicStrategy_STRANGLE_30_BTC_3",
  "HegicStrategy_STRANGLE_30_BTC_4",
] as const
 

export const availableStrategies = [
  ...v0Strategies,
  ...classicStrategies,
  ...inverseStrategies,
] as const